export const WORD_LIST = [
  'hello',
  'hi',
  'thanks',
  'please',
  'yes',
  'no',
  'how',
  'what',
  'where',
  'when',
  'good',
  'sorry',
  'help',
  'sure',
  'later',
  'okay',
  'bye',
  'welcome',
  'great',
  'congrats',
];

export const SENTENCE_LIST = [
  '/image',
  '/select',
  'How can I help you?',
  'What time is the meeting?',
  'Let me check on that.',
  "I'll get back to you shortly.",
  'Thank you for your help.',
  'Can you send me the details?',
  "I'm on my way.",
  'Please let me know if you need anything.',
  'Sorry for the inconvenience.',
  'That sounds great!',
  'I will look into it.',
  'Can we reschedule the call?',
  'I appreciate your understanding.',
  'It was nice talking to you.',
  'Could you please clarify that?',
  'Is there anything else?',
  "Let's catch up later.",
  "I'll be there in 10 minutes.",
  'Looking forward to your response.',
  'Have a great day!',
];

export const COMBO_BOX_OPTIONS = ['Option 1', 'Option 2', 'Option 3', 'Option 4', 'Option 5'];
